name: Aggiornamento Automatico Dati

on:
  schedule:
    # Esegue lo script ogni domenica alle 13:00 UTC
    - cron: '0 13 * * 0'
  workflow_dispatch: # Permette di lanciarlo anche manualmente da GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Installa dipendenze
        run: |
          cd estrai_dati
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Esegui lo script scraper
        run: |
          cd estrai_dati
          python aggiorna_dati.py

      - name: Committa e pusha i nuovi dati
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "aggiornamento dati - github action"
            git push
          else
            echo "Nessuna modifica da committare."
          fi